name: Bazel

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v2

    - name: deps
      # Install Bazel See: https://bazel.build/install/ubuntu
      run: |
           sudo apt install -y libaio-dev
    - name: Build
      # Build your program with clang
      working-directory: ${{github.workspace}}
      # Hacking due to there is a bug in either clang14 or libstdc++13 that the compiler is
      # complaining a consteval function is not constant expression.
      run: bazel build --action_env=CXX=clang++ --action_env=CC=clang --cxxopt="-Dconsteval=constexpr" ...

    - name: Test
      # Build and Execute tests
      working-directory: ${{github.workspace}}
      # Hacking due to there is a bug in either clang14 or libstdc++13 that the compiler is
      # complaining a consteval function is not constant expression.
      run: bazel test --action_env=CXX=clang++ --action_env=CC=clang --test_output=errors --cxxopt="-Dconsteval=constexpr" ...
